### ISSUE TITLE
Question about experiment in paper

### ISSUE THREAD

**Issue by GoldenSpark** [DingXiaoH/AOFP#1]
Hi ShawnDing, I've been watching this paper for a long time and it's so nice. But I still have a question about the experiment result on ImageNet in this paper. As far as I know, the FLOPs of ResNet-50 is about 4.09G. However,  we can figure out the FLOPs by 1.66G/(1-56.73%), which is only 3.84G. So I'm confused on it. Could you please explain it for me?

**Comment by ShawnDing1994** [comment]
Hi GoldenSpark,

We calculate the number of FLOPs in the same manner as the original ResNet paper (Deep Residual Learning ...). Please check Table. 1 in that paper.

Best Regards,
Xiaohan Ding



________________________________
shawnding@outlook.com

**Comment by junhuidai** [comment]
> Hi ShawnDing, I've been watching this paper for a long time and it's so nice. But I still have a question about the experiment result on ImageNet in this paper. As far as I know, the FLOPs of ResNet-50 is about 4.09G. However,  we can figure out the FLOPs by 1.66G/(1-56.73%), which is only 3.84G. So I'm confused on it. Could you please explain it for me?

Is your code working? I have problems. I can't run
