### ISSUE TITLE
ResNet and pytorch

### ISSUE THREAD

**Issue by Slawlight** [DingXiaoH/AOFP#2]
I am very interesting in this nice work. I am eager to the PyTorch implementation and the ResNet model.

**Comment by DingXiaoH** [comment]
In one or two weeks. (Because my experiments for CVPR just failed. I have plenty of time now. lol.)

**Comment by junhuidai** [comment]
> I am very interesting in this nice work. I am eager to the PyTorch implementation and the ResNet model.
Is your code working? I have problems. I can't run

**Comment by euminds** [comment]
I read the paper. The multi-path of this paper has greatly helped my current work. I hope to get Pytorch and ResNet related code as soon as possible. Thank you
