### ISSUE TITLE
Question about the demo of VGG16 on CIFAR-10

### ISSUE THREAD

**Issue by GoldenSpark** [DingXiaoH/AOFP#4]
Hi,  ShawnDing. I have an issue about the demo and could you please answer it for me?
The acc-top1 of VGG16 is 86.57% by using 'python aofp/aofp_standalone.py train' to train from scratch while the baseline in paper is 93.38% on CIFAR-10. 
What's the performance did you get by using 'python aofp/aofp_standalone.py train'?

**Comment by colorjam** [comment]
@GoldenSpark Hi,  did you see the following error when you train the model?
```
Traceback (most recent call last):
  File "aofp_standalone.py", line 9, in <module>
    from util_scripts.compression_calculat import calculate_vfs_flops
  File "/home/yanchenqian/repo/AOFP/util_scripts/compression_calculat.py", line 1, in <module>
    from tfm_constants import *
ModuleNotFoundError: No module named 'tfm_constants'
```

**Comment by DingXiaoH** [comment]
Thank you for being interested in this repo. I am checking it!

**Comment by DingXiaoH** [comment]
Reviewing the ancient codes is killing me. I think I'll just re-implement it in PyTorch in one or two weeks. Maybe that will save time for both readers and me.

**Comment by colorjam** [comment]
@DingXiaoH I just run the training code, the prec@1 is 93.7%, and the prec@5 is 99.61%. Reading TensorFlow code makes me crazy...  Looking forward your PyTorch version!

**Comment by junhuidai** [comment]
> @DingXiaoH I just run the training code, the prec@1 is 93.7%, and the prec@5 is 99.61%. Reading TensorFlow code makes me crazy...  Looking forward your PyTorch version!
Have you found  the Pytorch version？
